CREATE TABLE courier (
    id                      VARCHAR(64)      NOT NULL PRIMARY KEY,
    last_lat                DOUBLE PRECISION NOT NULL,
    last_lng                DOUBLE PRECISION NOT NULL,
    last_seen_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    total_distance_meters   DOUBLE PRECISION NOT NULL,
    version                 BIGINT           NOT NULL
);

CREATE TABLE store_entrance (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    courier_id  VARCHAR(64)      NOT NULL REFERENCES courier (id),
    store_name  VARCHAR(255)     NOT NULL,
    entered_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    lat         DOUBLE PRECISION NOT NULL,
    lng         DOUBLE PRECISION NOT NULL
);

CREATE INDEX idx_store_entrance_courier_store_time
    ON store_entrance (courier_id, store_name, entered_at);
